# Site settings
title: OntoWiki
email: your-email@domain.com
url: http://ontowiki.net
description: "Semantic Data Wiki and Linked Data Publishing Engine"
# The Semantic Web Tool for Agile, Distributed Knowledge Engineering

# Color settings (hex-codes with the leading hash)
color:
  primary-dark: '#000000'
  primary-light: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: "Agile Knowledge Engineering and Semantic Web (AKSW)"
footer_link: http://aksw.org/Imprint.html

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: aksw
    logo: globe
    url: http://aksw.org/Projects/OntoWiki

participate:
  - title: stackoverflow
    logo: stack-overflow
    url: http://stackoverflow.com/questions/tagged/ontowiki
  - title: github
    url: https://github.com/AKSW/OntoWiki

advertised:
  - title: download
    url: "#download"
  - title: documentation
    logo: book
    url: "http://docs.ontowiki.net/"

# Build settings
markdown: kramdown
permalink: pretty
