# Site settings
title: OntoWiki
email: your-email@domain.com
url: http://ontowiki.net
description: "Semantic data wiki as well as Linked Data publishing engine"
# The Semantic Web Tool for Agile, Distributed Knowledge Engineering

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "Agile Knowledge Engineering and Semantic Web (AKSW)"
footer_link: http://aksw.org/Imprint.html

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/ontowiki
  - title: github
    url: https://github.com/AKSW/OntoWiki
  - title: aksw
    logo: globe
    url: http://aksw.org/Projects/OntoWiki
  - title: documentation
    logo: book
    url: "http://docs.ontowiki.net/"
  - title: download
    url: "#download"

# Build settings
markdown: kramdown
permalink: pretty
